spring.application.name=user-service
spring.threads.virtual.enabled=${SPRING_THREADS_VIRTUAL_ENABLED:true}
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/stock_database?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8081
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.lettuce.pool.enabled=true
