global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: seckill-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - seckill-service:18085
        labels:
          service: seckill-service
          project: flashsale

  - job_name: mysql-exporter
    static_configs:
      - targets:
          - mysql-exporter:9104
        labels:
          service: mysql
          project: flashsale

  - job_name: kafka-exporter
    static_configs:
      - targets:
          - kafka-exporter:9308
        labels:
          service: kafka
          project: flashsale
