[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name   forward
    Listen 0.0.0.0
    Port   24224

[FILTER]
    Name         parser
    Match        docker.goods-service
    Key_Name     log
    Parser       app_json
    Reserve_Data On

[OUTPUT]
    Name   stdout
    Match  *
    Format json_lines

[OUTPUT]
    Name              es
    Match             docker.goods-service
    Host              elasticsearch
    Port              9200
    Index             goods-service-logs
    Logstash_Format   On
    Logstash_Prefix   goods-service
    Suppress_Type_Name On
    Retry_Limit       False
