FROM node:20-alpine AS frontend-builder

WORKDIR /frontend

COPY stock-frontend/package*.json ./
RUN npm ci

COPY stock-frontend/ ./
RUN npm run build

FROM nginx:alpine

COPY stock-backend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=frontend-builder /frontend/dist /usr/share/nginx/html
